# Config file for CelebA dataset (200k)

output_dir: 'gdrive/My Drive/depth/'
structure: 'linear'
device_id: ('3')
dataset:
  img_dir: 'datasets/img_align_celeba/img_align_celeba'
  folder: False
  resolution: 128
sched:
  epochs: [2,4,4,4,4,8]
